language: python

python:
  - 2.7

services: mysql

addons:
  ssh_known_hosts: 37.139.2.116

before_install:
  - openssl aes-256-cbc -K $encrypted_65a296283a37_key -iv $encrypted_65a296283a37_iv -in key_hasker.enc -out key_hasker -d

install:
  - python --version

#  - pip install -r requirements.txt
#  - mysql -e 'CREATE DATABASE  IF NOT EXISTS hasker;'
#  - python manage.py migrate --noinput

script:
  - python --version

after_success:
  - ./deploy.sh