version: "2"

services:
  mysql:
    restart: always
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - ../volumes/mysql57:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=hasker

  nginx:
    image: nginx:latest
    volumes: 
    - "./hasker/static:/opt/static"
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/log:/var/log/nginx
    ports:
    - "8000:8000"
    links:
    - "backend"
  
  backend:
    restart: always
    image: hasker_server:local
    depends_on:
    - "mysql"
    links:
    - "mysql"