"""
Django settings for hasker project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from hasker.settings import *

# mysql://b64817464909a3:13313200@eu-cdbr-west-02.cleardb.net/heroku_20c5cfc0c73b545?reconnect=true

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST':'eu-cdbr-west-02.cleardb.net',
        'PORT':'3306',
        'USER': 'b64817464909a3',
        'PASSWORD': '13313200',
        'NAME': 'heroku_20c5cfc0c73b545',
        'TEST':{
            'NAME':'hasker_test'
        }
    }
}

